version: '3'
services:
  backend:
    build: .
    volumes:
      - .:/app
      - ./backend:/app
    ports:
      - "5000:5000"

#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile_frontend
#    # Configure frontend service as needed
