version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    container_name: fadStackTemplate_backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    container_name: fadStackTemplate_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    ports:
      - "4200:4200"
