# Use an official Python runtime as a parent image
FROM python:3.12.1

# Create and set the working directory
WORKDIR /backend

# Copy the contents of the local backend directory to the container at /app
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port your app runs on
EXPOSE 5000

ENV PYTHONPATH=/app:$PYTHONPATH

# Command to run your application
CMD ["python", "app/app.py"]
